Add foreignKey validation for a full dictionary
overture-stack/js-lectern-client pull request #36
Opened 2023-08-01 13:15 UTC by mauroz77

Resolves [#35](https://github.com/overture-stack/js-lectern-client/issues/35)

This is an implementation proposal for the validation of foreign keys between schemas. It validates that a field or set of fields (equivalent to a composite fk in relational databases) matches at least one record in a record in another schema.

## Summary of main changes

- New `processRecords` function to validate schemas data against a dictionary. It calls `processRecords` to run validations per schema but also runs a cross-schema validation pipeline.
- New `runCrossSchemaValidationPipeline` function, homologous to `runValidationPipeline`, to run validation functions of type `CrossSchemaValidationFunction`
- New type `CrossSchemaValidationFunction` to describe functions that apply over a full dictionary.

2023-08-01 13:25 UTC, justincorrigible commented on src/records-operations.ts
> +    return _.differenceWith(arrayA, arrayB, (a, b) => a[1].join('_') == b[1].join('_'));
- `_`: Destructuring import here decreases confusion between lodash's "underscore", with the strings in the join methods.
- `===`: we should be able to use "identical" comparison between the two strings

```suggestion
import { differenceWith } from 'lodash';

/**
 * Calculates the difference between 2 records (similar to a set difference). Returns rows in `recordA` which are not present
 * in `recordB`. Two rows are equal if their values are the same.
 * @param recordA Record A. The returned value of this function is a subset of this record.
 * @param recordB Record B. Elements to be substracted from Record A.
 */
export const calculateDifference = (recordA: Record<number, string[]>, recordB: Record<number, string[]>): any[][]  => {
    const arrayA = recordToArray(recordA);
    const arrayB = recordToArray(recordB);
    return differenceWith(arrayA, arrayB, (a, b) => a[1].join('_') === b[1].join('_'));
```

2023-08-01 13:28 UTC, justincorrigible commented on src/schema-error-messages.ts
> +function getForeignKeyErrorMsg(errorData: any) {
though hoisting works here very well, I may recommend relocating this to line 22, so the function is defined before being used to improve readability.

2023-08-02 20:57 UTC, joneubank requested changes

2023-08-02 20:57 UTC, joneubank commented on src/schema-functions.ts
> +        const foreignSchemaData = schemasData[foreignKeyDefinition.schema];
`localSchemaData` and `foreignSchemaData` could be `undefined` by accessing their values using brackets even though TS does not indicate this.  We should make sure that each of these constants is at least set to be an empty array if no data records are provided for this schema:
```suggestion
        const localSchemaData = schemasData[schemaDef.name] || [];
        const foreignSchemaData = schemasData[foreignKeyDefinition.schema] || [];
```

2023-08-02 20:57 UTC, joneubank commented on src/schema-functions.ts
> + * dataset and the value is an arra with the values in the row for the fields defined in `fields`.
```suggestion
 * dataset and the value is an array with the values in the row for the fields defined in `fields`.
```

2023-08-02 20:57 UTC, joneubank commented on src/schema-functions.ts
> + * @returns Record with the format <id, [valueField1, valueField2, ... valueFiledN]>.
`id` is wrong here, it should be the line number from the input tsv/sheet to match the other errors.

2023-08-02 20:57 UTC, joneubank commented on src/schema-functions.ts
> +const buildRecordsFromDataset = (dataset: SchemaData, fields: string[]): Record<number, string[]> => {
This name, even with description, is unclear as to what this does or what its purpose is.

Perhaps it could be: `buildCompositeKeyForRecords`?

Additionally, why are we building a record here when everything that uses the output from this function immediately converts it into a tuple?  Could this output a tuple instead like `[number, string[]][]`?

2023-08-02 20:57 UTC, joneubank commented on src/records-operations.ts
> +};
We need to do some cleanup here to remove the `any` types. We shouldn't be using methods with `any` as a return type - unless that is precisely what we expect to happen, and that is not the case here. Instead we can clearly indicate the structure that will be returned since we know what it is.

The current method `recordToArray` is actually returning the type `(number | string[])[][]`, according to TS if the `any[]` return type declaration is removed. We want to return an array of tuples of the shape [number, string[]][] instead, which we can do with a return type declaration. The whole thing can be simplified to:

```ts
const recordToArray = (record: Record<number, string[]>): [number, string[]][] =>
  Object.keys(record).map((x) => {
    const idx = parseInt(x);
    return [idx, record[idx]];
  });
```

Next, based on the actual usage of `calculateDifference` in `validateForeignKey`, there is an expected output type from this method... another array of tuples with the index and the foreign key values. The return type for this can be similarly corrected.

Also, the joining of the foreign key values by underscore could have edge case errors. It is possible that underscores are valid characters in the values, and combining them this way could match values you might not expect. Example: `["as_df", "gh"].join('_')` would match `["as", "df_gh"].join('_')`. It might simplify the whole process to be comparing objects that include the property names: `{propA: "as_df", propB: "gh" }`. This would also be easier to read in the error message when the value is printed out. We can change the function signature to accomplish all this:

 ```ts
export const findMissingForeignKeys = (recordA: Record<number, Record<string, string | string[]>>, recordB: Record<number, Record<string, string | string[]>>): [number, string | string[]][]
```

To accomplish this we will want to change the output type of `buildRecordsFromDataset` and that will probably make `recordToArray` unnecessary as well.

2023-08-02 20:57 UTC, joneubank commented on src/schema-functions.ts
> +const buildRecordsFromDataset = (dataset: SchemaData, fields: string[]): Record<number, string[]> => {
I left a comment on records-operations that would imply changes to the output of this function as well, read that comment first. The new return type could be `Record<string, string | string[]>` (don't need to pass the index separately).

2023-08-04 15:01 UTC, mauroz77 commented on src/schema-functions.ts
> +const buildRecordsFromDataset = (dataset: SchemaData, fields: string[]): Record<number, string[]> => {
I like`buildCompositeKeyForRecords`. I was also thinking about `selectFieldsFromDataset` as an alternative. This function is now used for getting the values to evaluate in the FK but also it can be used in the coming implementation for the unique key (schema level) and maybe the unique (field level) restriction (It would need a minor refactoring to use it). That’s why I’m suggesting `selectFieldsFromDataset` but like`buildCompositeKeyForRecords` also works because they are all keys at the end. Open to comments.

As for the description, maybe something like:

A “select” function that retrieves specific fields from the **`dataset`** as an array of strings, as well as the numeric position of each row in the dataset.

Does it look ok?

2023-08-11 18:29 UTC, joneubank commented on src/schema-functions.ts
> +const buildRecordsFromDataset = (dataset: SchemaData, fields: string[]): Record<number, string[]> => {
`selectFieldsFromDataset` is a good name as well. naming is hard.

2023-08-14 13:06 UTC, joneubank approved these changes
Great stuff! Appreciate the changes!

2023-08-14 13:06 UTC, merged